---
# This schema describes the yaml format for a data product packet suite.
type: map
mapping:
  # Description of the packet suite.
  description:
    type: str
    required: False
  # Many "with" dependencies are automatically deduced and included by
  # the generator. If you want to manually add a "with" statement, you
  # can list the names of the packages here.
  with:
    seq:
      - type: str
    required: False
  # List of packets to include in the suite.
  packets:
    seq:
      - type: map
        mapping:
          # Name of the packet.
          name:
            type: str
            required: True
          # Description of the packet.
          description:
            type: str
            required: False
          # Identifier for the packet (in CCSDS this would be the APID).
          id:
            type: int
            required: True
          # Is the packet enabled or disabled upon initialization. By default
          # packets are enabled is this is not specified.
          enabled:
            type: bool
            required: False
          # The period (in ticks) in which to build the packet. This is the value set upon
          # initialization.
          period:
            type: str
            required: True
          # The offset (in ticks) at which to stagger the construction of this packet. An offset of
          # 5 will cause the packet to be built according to its period, but 5 ticks later than expected.
          # Note that the offset should be less than the period otherwise it will be mod'ed by the period
          # so that it is less than the period. For example, if the period is 3 and the offset is set to
          # 5, the actual offset used will be 2.
          #
          # This field can be used to stagger packet creation, allowing the user to evenly distribute
          # the work that this component does, so as to not cause cycle slips when many packets need to
          # be built on the same tick.
          offset:
            type: str
            required: False
          # If set to true then the packet is timestamped with the time found on the incoming Tick.T
          # instead of the current time as fetched via the time connector. By default, if not specified
          # this value is set to False.
          use_tick_timestamp:
            type: bool
            required: False
          # List of data products to include in packet
          data_products:
            seq:
              - type: map
                mapping:
                  # The name of the data product. The name should be in the format
                  # Component_Name.Data_Product_Name. The name is a required field unless
                  # pad_bytes is specified.
                  name:
                    type: str
                    required: False
                  # Produce an event if the data product is ever not available when fetched. By default
                  # this is false.
                  event_on_missing:
                    type: bool
                    required: False
                  # Use this data product's timestamp as the packet timestamp. This may only be set true for
                  # a single data product per packet. By default this value is false.
                  use_timestamp:
                    type: bool
                    required: False
                  # Include this data product's timestamp just before its value in the actual packet.
                  # By default this value is false.
                  include_timestamp:
                    type: bool
                    required: False
                  # Pad bytes can be used to insert a n-number of bytes of unused data into a packet. This is
                  # also useful to add in spacing for data products that do not exist yet, but are expected
                  # in the packet. Pad bytes can only be specified if no other fields are specified.
                  pad_bytes:
                    type: int
                    required: False
            range:
              min: 1
            required: True
    # A packet suite must have at least one packet.
    range:
      min: 1
    required: True
