#!/usr/bin/env python3

# Build our dependencies using the build system.
# This is necessary because some of the depdencies we
# have are autogenerated.
from util import pydep

pydep.build_py_deps()

# Noe that the autocode has been built, import
# the autocoded module.
from example_record import Example_Record

# Main:
if __name__ == "__main__":
    print("create and print example record:")
    example1 = Example_Record(Value_1=2, Value_2=-1, Value_3=1, Value_4=0.5)
    print(str(example1))
    print()
    print(str(example1.to_tuple_string()))
    print()
    print(str(example1.to_byte_array().hex()))
    print()
    print(str(example1.to_byte_string()))
    print()

    print("serializing and deserializing example record:")
    data = example1.to_byte_array()
    example2 = Example_Record.create_from_byte_array(data)
    assert example1 == example2
    print("done.")
