--------------------------------------------------------------------------------
-- Interrupt_Listener Component Implementation Body
--------------------------------------------------------------------------------

package body Component.Interrupt_Listener.Implementation is

   ---------------------------------------
   -- Invokee connector primitives:
   ---------------------------------------
   -- Interrupt data generated by the custom procedure is sent back via the return type.
   overriding function Interrupt_Data_Type_Return (Self : in out Instance) return Interrupt_Data_Type is
   begin
      return Self.The_Signal.Get_Data;
   end Interrupt_Data_Type_Return;

end Component.Interrupt_Listener.Implementation;
