name: Prove All SPARK Packages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  refs:
    uses: ./.github/workflows/_refs.yml
  compile_job:
    needs: refs
    name: prove_all
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.refs.outputs.image }}
      options: --user root
    steps:
      - run: echo "Starting job triggered by a ${{ github.event_name }} event on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Checking out ${{ github.repository }} on branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Prove all SPARK packages
        run: bash env/github_run.sh "redo prove_all"
      - name: Archive prove logs
        if: always() # Make sure this runs even if `redo prove_all` fails
        uses: actions/upload-artifact@v4
        with:
          name: prove_logs
          path: ${{ github.workspace }}/build
          if-no-files-found: ignore
      - run: echo "Finished with status - ${{ job.status }}."
        if: always()
