name: Build All Documentation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  refs:
    uses: ./.github/workflows/_refs.yml
  compile_job:
    needs: refs
    name: publish_all
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.refs.outputs.image }}
      options: --user root
    steps:
      - run: echo "Starting job triggered by a ${{ github.event_name }} event on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Checking out ${{ github.repository }} on branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build all documentation
        run: bash env/github_run.sh "redo publish"
      - run: echo "Finished with status - ${{ job.status }}."
        if: always()
