name: Check Style
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  compile_job:
    name: style_all
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lasp/adamant:0.1
      options: --user root
    steps:
      - run: echo "Starting job triggered by a ${{ github.event_name }} event on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Checking out ${{ github.repository }} on branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check all style
        run: bash env/github_run.sh "redo style_all"
      - name: Archive logs for failed style checks
        if: always() # Make sure this runs even if `redo style_all` fails
        uses: actions/upload-artifact@v4
        with:
          name: style_logs
          path: ${{ github.workspace }}/build
          if-no-files-found: ignore
      - run: echo "Finished with status - ${{ job.status }}."
        if: always()
